export const COLLECTIONS = {
  products: 'products',
  orders: 'orders',
  users: 'users',
  packages: 'packages',
  bulkOrders: 'bulkOrders',
  wholesaleAccounts: 'wholesaleAccounts',
  settings: 'settings',
  marketingAds: 'marketingAds',
  sharedCheckouts: 'sharedCheckouts',
  serviceCategories: 'serviceCategories',
  serviceProviders: 'serviceProviders',
  services: 'services',
  serviceBookings: 'serviceBookings',
  serviceReviews: 'serviceReviews',
  providerAvailability: 'providerAvailability',
} as const;
