import { SERVICE_CATALOG } from '@/lib/service-catalog';
import type { ServiceProvider, ServiceListing } from '@/lib/types/services';
import { getDefaultWeeklySlots } from '@/lib/services-utils';

export const SEED_SERVICE_CATEGORIES = SERVICE_CATALOG.map((c) => ({
  id: c.id,
  name: c.name,
  description: c.description,
  serviceTypes: c.serviceTypes,
  sortOrder: c.sortOrder,
  isActive: true,
}));

export const SEED_SERVICE_PROVIDERS: Omit<ServiceProvider, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'provider-glow-studio',
    name: 'Amina Nakato',
    businessName: 'Glow Studio Kampala',
    phone: '0772123456',
    whatsapp: '0772123456',
    email: 'hello@glowstudio.ug',
    address: 'Plot 12, Acacia Avenue, Kololo',
    city: 'Kampala',
    profileImage: '',
    bio: 'Award-winning makeup artist and bridal specialist with 8+ years of experience across East Africa.',
    experienceYears: 8,
    categoryIds: ['makeup-services', 'bridal-services', 'eyelash-eyebrow-services'],
    portfolioImages: [],
    isVerified: true,
    isActive: true,
    mobileServiceEnabled: true,
    serviceRadiusKm: 15,
    serviceAreas: ['Kampala', 'Kololo', 'Nakasero', 'Ntinda'],
    travelFee: 30000,
    rating: 4.9,
    reviewCount: 124,
    completedJobs: 380,
  },
  {
    id: 'provider-queen-braids',
    name: 'Grace Akello',
    businessName: 'Queen Braids & Beauty',
    phone: '0783456789',
    whatsapp: '0783456789',
    email: 'book@queenbraids.ug',
    address: 'Wandegeya Market Road',
    city: 'Kampala',
    profileImage: '',
    bio: 'Specialist in knotless braids, Ghana weaving, and protective styles. Home visits available.',
    experienceYears: 6,
    categoryIds: ['hair-services', 'home-beauty-services'],
    portfolioImages: [],
    isVerified: true,
    isActive: true,
    mobileServiceEnabled: true,
    serviceRadiusKm: 20,
    serviceAreas: ['Kampala', 'Wandegeya', 'Makerere', 'Bukoto'],
    travelFee: 25000,
    rating: 4.8,
    reviewCount: 210,
    completedJobs: 520,
  },
  {
    id: 'provider-serenity-spa',
    name: 'Diana Tumusiime',
    businessName: 'Serenity Spa & Wellness',
    phone: '0701234567',
    whatsapp: '0701234567',
    email: 'spa@serenity.ug',
    address: 'Bugolobi, Luthuli Avenue',
    city: 'Kampala',
    profileImage: '',
    bio: 'Licensed massage therapist offering spa packages, facials, and wellness consultations.',
    experienceYears: 10,
    categoryIds: ['spa-wellness', 'skincare-services', 'luxury-services'],
    portfolioImages: [],
    isVerified: true,
    isActive: true,
    mobileServiceEnabled: false,
    serviceRadiusKm: 0,
    serviceAreas: ['Bugolobi', 'Kampala'],
    travelFee: 0,
    rating: 4.7,
    reviewCount: 89,
    completedJobs: 245,
  },
  {
    id: 'provider-nail-luxe',
    name: 'Patricia Namukasa',
    businessName: 'Nail Luxe Studio',
    phone: '0756789012',
    whatsapp: '0756789012',
    email: 'nails@nailuxe.ug',
    address: 'Garden City Mall, Level 2',
    city: 'Kampala',
    profileImage: '',
    bio: 'Premium nail art, gel polish, and bridal nail services in a luxury studio setting.',
    experienceYears: 5,
    categoryIds: ['nail-services', 'bridal-services'],
    portfolioImages: [],
    isVerified: false,
    isActive: true,
    mobileServiceEnabled: true,
    serviceRadiusKm: 10,
    serviceAreas: ['Kampala', 'Naguru', 'Bugolobi'],
    travelFee: 20000,
    rating: 4.6,
    reviewCount: 67,
    completedJobs: 190,
  },
];

export const SEED_SERVICE_LISTINGS: Omit<ServiceListing, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'svc-bridal-makeup-glow',
    slug: 'bridal-makeup-glow-studio',
    name: 'Bridal Makeup',
    description: 'Flawless bridal makeup with premium products, skin prep, and a touch-up kit for your big day.',
    benefits: ['Long-lasting finish', 'Skin prep included', 'Trial session available'],
    categoryId: 'makeup-services',
    serviceType: 'Bridal Makeup',
    providerId: 'provider-glow-studio',
    durationMinutes: 120,
    basePrice: 350000,
    galleryImages: [],
    isFeatured: true,
    isPopular: true,
    isActive: true,
    isArchived: false,
    supportsMobile: true,
    supportsInStudio: true,
    location: 'Kololo, Kampala',
    bookingCount: 86,
    viewCount: 420,
    rating: 4.9,
    reviewCount: 52,
    sortOrder: 1,
  },
  {
    id: 'svc-knotless-braids',
    slug: 'knotless-braids-queen',
    name: 'Knotless Braids',
    description: 'Lightweight, scalp-friendly knotless braids with premium braiding hair. Styles last 4–6 weeks.',
    benefits: ['Gentle on scalp', 'Premium hair included', 'Home service available'],
    categoryId: 'hair-services',
    serviceType: 'Knotless Braids',
    providerId: 'provider-queen-braids',
    durationMinutes: 300,
    basePrice: 280000,
    galleryImages: [],
    isFeatured: true,
    isPopular: true,
    isActive: true,
    isArchived: false,
    supportsMobile: true,
    supportsInStudio: true,
    location: 'Wandegeya, Kampala',
    bookingCount: 142,
    viewCount: 890,
    rating: 4.8,
    reviewCount: 98,
    sortOrder: 2,
  },
  {
    id: 'svc-deep-tissue-massage',
    slug: 'deep-tissue-massage-serenity',
    name: 'Deep Tissue Massage',
    description: 'Therapeutic deep tissue massage to relieve tension, improve circulation, and restore balance.',
    benefits: ['Licensed therapist', 'Aromatherapy oils', 'Spa ambiance'],
    categoryId: 'spa-wellness',
    serviceType: 'Deep Tissue Massage',
    providerId: 'provider-serenity-spa',
    durationMinutes: 90,
    basePrice: 180000,
    galleryImages: [],
    isFeatured: true,
    isPopular: false,
    isActive: true,
    isArchived: false,
    supportsMobile: false,
    supportsInStudio: true,
    location: 'Bugolobi, Kampala',
    bookingCount: 64,
    viewCount: 310,
    rating: 4.7,
    reviewCount: 41,
    sortOrder: 3,
  },
  {
    id: 'svc-gel-manicure',
    slug: 'gel-manicure-nail-luxe',
    name: 'Gel Manicure & Nail Art',
    description: 'Long-lasting gel polish with optional nail art designs. Perfect for events and everyday elegance.',
    benefits: ['Chip-resistant gel', 'Custom nail art', 'Hand massage included'],
    categoryId: 'nail-services',
    serviceType: 'Gel Polish',
    providerId: 'provider-nail-luxe',
    durationMinutes: 75,
    basePrice: 85000,
    galleryImages: [],
    isFeatured: false,
    isPopular: true,
    isActive: true,
    isArchived: false,
    supportsMobile: true,
    supportsInStudio: true,
    location: 'Garden City, Kampala',
    bookingCount: 95,
    viewCount: 540,
    rating: 4.6,
    reviewCount: 38,
    sortOrder: 4,
  },
  {
    id: 'svc-lash-extensions',
    slug: 'lash-extensions-glow',
    name: 'Eyelash Extensions',
    description: 'Classic and volume lash extensions applied by certified lash technicians for a natural glam look.',
    benefits: ['Certified technician', 'Hypoallergenic adhesive', 'Aftercare guide'],
    categoryId: 'eyelash-eyebrow-services',
    serviceType: 'Eyelash Extensions',
    providerId: 'provider-glow-studio',
    durationMinutes: 120,
    basePrice: 150000,
    galleryImages: [],
    isFeatured: true,
    isPopular: true,
    isActive: true,
    isArchived: false,
    supportsMobile: false,
    supportsInStudio: true,
    location: 'Kololo, Kampala',
    bookingCount: 73,
    viewCount: 280,
    rating: 4.8,
    reviewCount: 29,
    sortOrder: 5,
  },
  {
    id: 'svc-home-facial',
    slug: 'home-facial-serenity',
    name: 'Home Facial Service',
    description: 'Luxury facial treatment brought to your home. Deep cleansing, hydration, and glow boost.',
    benefits: ['Travel to you', 'Premium products', 'Personalized skin analysis'],
    categoryId: 'home-beauty-services',
    serviceType: 'Home Facial Service',
    providerId: 'provider-serenity-spa',
    durationMinutes: 90,
    basePrice: 220000,
    galleryImages: [],
    isFeatured: false,
    isPopular: true,
    isActive: true,
    isArchived: false,
    supportsMobile: true,
    supportsInStudio: false,
    location: 'Kampala & surrounding areas',
    bookingCount: 48,
    viewCount: 195,
    rating: 4.7,
    reviewCount: 22,
    sortOrder: 6,
  },
];

export const SEED_PROVIDER_AVAILABILITY = SEED_SERVICE_PROVIDERS.map((p) => ({
  id: p.id,
  providerId: p.id,
  weeklySlots: getDefaultWeeklySlots(),
  blackoutDates: [] as string[],
  slotDurationMinutes: 60,
}));
