import { Product } from '@/lib/types/database';
import { Package } from '@/lib/types/wholesale';

const now = new Date();

export const SEED_PRODUCTS: Omit<Product, 'createdAt' | 'updatedAt'>[] = [
  {
    id: '1',
    name: 'Silk Blouse',
    sku: 'SLB-001',
    description: 'Elegant silk blouse crafted for timeless sophistication.',
    category: 'Clothing',
    price: 450000,
    originalPrice: 600000,
    stock: 45,
    rating: 4.5,
    reviews: 86,
    image: '',
    images: [],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Cream', 'Navy'],
    details: ['100% silk', 'Dry clean recommended', 'Relaxed fit'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '2',
    name: 'Cashmere Sweater',
    sku: 'CSW-002',
    description: 'Premium cashmere blend sweater for luxurious comfort.',
    category: 'Clothing',
    price: 850000,
    originalPrice: 1200000,
    stock: 28,
    rating: 5,
    reviews: 128,
    image: '',
    images: [],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Cream', 'Navy', 'Camel'],
    details: ['45% Cashmere blend', 'Hand-finished seams', 'Machine washable'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '3',
    name: 'Luxury Face Cream',
    sku: 'LFC-003',
    description: 'Rich hydrating face cream with botanical extracts.',
    category: 'Beauty',
    price: 280000,
    originalPrice: 350000,
    stock: 62,
    rating: 4.8,
    reviews: 94,
    image: '',
    images: [],
    sizes: [],
    colors: [],
    details: ['Dermatologist tested', 'Vegan formula', '50ml jar'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '4',
    name: 'Wellness Retreat Set',
    sku: 'WRS-004',
    description: 'Complete wellness kit for daily self-care rituals.',
    category: 'Wellness',
    price: 200000,
    stock: 35,
    rating: 4.6,
    reviews: 52,
    image: '',
    images: [],
    sizes: [],
    colors: [],
    details: ['Essential oils included', 'Gift-ready packaging'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '5',
    name: 'Designer Sunglasses',
    sku: 'DSG-005',
    description: 'UV-protected designer sunglasses with premium frames.',
    category: 'Accessories',
    price: 700000,
    stock: 18,
    rating: 4.7,
    reviews: 41,
    image: '',
    images: [],
    sizes: [],
    colors: ['Black', 'Tortoise'],
    details: ['100% UV protection', 'Polarized lenses'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '6',
    name: 'Premium Leather Wallet',
    sku: 'PLW-006',
    description: 'Hand-stitched leather wallet with card slots.',
    category: 'Accessories',
    price: 320000,
    stock: 8,
    rating: 4.5,
    reviews: 37,
    image: '',
    images: [],
    sizes: [],
    colors: ['Black', 'Brown'],
    details: ['Full-grain leather', 'RFID blocking'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Low Stock',
  },
  {
    id: '7',
    name: 'Organic Skincare Trio',
    sku: 'OST-007',
    description: 'Three-step organic skincare routine set.',
    category: 'Beauty',
    price: 350000,
    originalPrice: 450000,
    stock: 40,
    rating: 4.9,
    reviews: 112,
    image: '',
    images: [],
    sizes: [],
    colors: [],
    details: ['Organic certified', 'Cruelty-free'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
  {
    id: '8',
    name: 'Silk Pillowcase',
    sku: 'SPK-008',
    description: 'Mulberry silk pillowcase for hair and skin care.',
    category: 'Home',
    price: 180000,
    stock: 55,
    rating: 4.4,
    reviews: 63,
    image: '',
    images: [],
    sizes: ['Standard', 'King'],
    colors: ['Champagne', 'Blush', 'White'],
    details: ['22 momme silk', 'Hidden zipper'],
    isWholesaleEnabled: true,
    minOrderQuantity: 10,
    maxOrderQuantity: null,
    status: 'Active',
  },
];

export const SEED_PACKAGES: Omit<Package, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'pkg-1',
    name: 'Beauty Essentials Bundle',
    description: 'Complete skincare starter pack with luxury products',
    items: [
      { productId: '3', quantity: 1 },
      { productId: '7', quantity: 1 },
    ],
    rule: { type: 'fixed' },
    pricingMode: 'custom',
    basePrice: 630000,
    discountedPrice: 550000,
    savingsPercentage: 12.7,
    isActive: true,
  },
  {
    id: 'pkg-2',
    name: 'Clothing Collection',
    description: 'Mix and match premium clothing pieces',
    items: [
      { productId: '1', quantity: 1 },
      { productId: '2', quantity: 1 },
    ],
    rule: { type: 'mix-and-match', itemLimit: 2 },
    pricingMode: 'custom',
    basePrice: 1300000,
    discountedPrice: 1100000,
    savingsPercentage: 15.4,
    isActive: true,
  },
  {
    id: 'pkg-3',
    name: 'Wellness Starter Kit',
    description: 'Everything you need for daily wellness',
    items: [
      { productId: '4', quantity: 2 },
      { productId: '8', quantity: 1 },
    ],
    rule: { type: 'customizable' },
    pricingMode: 'custom',
    basePrice: 580000,
    discountedPrice: 520000,
    savingsPercentage: 10.3,
    isActive: true,
  },
];

export const SEED_TIMESTAMP = now;
