export const TABLES = {
  products: 'products',
  orders: 'orders',
  profiles: 'profiles',
  packages: 'packages',
  bulkOrders: 'bulk_orders',
  wholesaleAccounts: 'wholesale_accounts',
  settings: 'settings',
  sharedCheckouts: 'shared_checkouts',
  sharedBookings: 'shared_bookings',
  suppliers: 'suppliers',
  serviceCategories: 'service_categories',
  serviceProviders: 'service_providers',
  services: 'services',
  serviceBookings: 'service_bookings',
  serviceReviews: 'service_reviews',
  productReviews: 'product_reviews',
  providerAvailability: 'provider_availability',
  contactMessages: 'contact_messages',
} as const;

/** @deprecated Use TABLES */
export const COLLECTIONS = {
  products: TABLES.products,
  orders: TABLES.orders,
  users: TABLES.profiles,
  packages: TABLES.packages,
  bulkOrders: TABLES.bulkOrders,
  wholesaleAccounts: TABLES.wholesaleAccounts,
  settings: TABLES.settings,
  marketingAds: TABLES.settings,
  sharedCheckouts: TABLES.sharedCheckouts,
  sharedBookings: TABLES.sharedBookings,
  suppliers: TABLES.suppliers,
  serviceCategories: TABLES.serviceCategories,
  serviceProviders: TABLES.serviceProviders,
  services: TABLES.services,
  serviceBookings: TABLES.serviceBookings,
  serviceReviews: TABLES.serviceReviews,
  productReviews: TABLES.productReviews,
  providerAvailability: TABLES.providerAvailability,
  contactMessages: TABLES.contactMessages,
} as const;
